# Generated by Django 5.2.11 on 2026-02-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
