# Generated by Django 5.2.11 on 2026-02-25 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_rentalitem_created_at_remove_rentalitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
