# Generated by Django 5.2.11 on 2026-02-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalitem_created_at_rentalitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units available'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Store item specifications as JSON'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.CharField(choices=[('aerial', 'Aerial Work Platforms'), ('concrete', 'Concrete & Masonry'), ('earthmoving', 'Earth Moving Equipment'), ('power_tools', 'Power Tools'), ('material_handling', 'Material Handling'), ('generators', 'Generators'), ('scaffolding', 'Scaffolding'), ('cleaning', 'Cleaning Equipment')], max_length=50),
        ),
    ]
