# Generated by Django 5.2.11 on 2026-02-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalitem_quantity_rentalitem_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='30% advance payment made at booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='specifications',
            field=models.JSONField(blank=True, default={'Platform Capacity': '', 'Platform Height': '', 'Platform Size': '', 'Weight': ''}, help_text='Store item specifications as JSON'),
        ),
    ]
