# Generated by Django 5.2.11 on 2026-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_booking_advance_paid_alter_rentalitem_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
