# Generated by Django 5.2.11 on 2026-02-27 04:33

import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_booking_advance_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='specifications',
            field=models.JSONField(blank=True, default=rentals.models.get_default_specifications, help_text='Store item specifications as JSON'),
        ),
    ]
