# Generated by Django 5.2.11 on 2026-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_rentalitem_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
