# Generated by Django 5.2.11 on 2026-03-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='agreement_pdf',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AGREEMENT_PENDING', 'Agreement Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.CharField(choices=[('construction_power_tools', '🔧 Construction & Power Tools'), ('home_improvement', '🏡 Home Improvement Tools'), ('garden_outdoor', '🌿 Garden & Outdoor Equipment'), ('electrical_electronics', '⚡ Electrical & Electronics'), ('event_party', '🎉 Event & Party Equipment'), ('cameras_media', '📷 Cameras & Media Equipment'), ('heavy_machinery', '🚜 Heavy Machinery'), ('hand_tools', '🛠 Hand Tools'), ('camping_outdoor', '🏕 Camping & Outdoor Gear'), ('vehicle_transport', '🚗 Vehicle & Transport Rentals')], max_length=50),
        ),
    ]
