# Generated by Django 5.2.11 on 2026-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_booking_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='transaction_id',
            new_name='advance_transaction_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Refund Pending'), ('PROCESSED', 'Refund Processed'), ('FAILED', 'Refund Failed')], default='NOT_APPLICABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ADVANCE_PAID', 'Advance Paid'), ('BALANCE_PAID', 'Balance Paid'), ('FULLY_PAID', 'Fully Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('AGREEMENT_PENDING', 'Agreement Pending'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
